// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm0kDZSpze-icEfz8myZiYd16SkJMmdyA',
    appId: '1:225418999366:web:69ed0234959212def8fc47',
    messagingSenderId: '225418999366',
    projectId: 'fypar-819e4',
    authDomain: 'fypar-819e4.firebaseapp.com',
    storageBucket: 'fypar-819e4.appspot.com',
    measurementId: 'G-MM6ZW71VMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb3Dkvcai88ZDDXz01k82JuXg7VXAS3tk',
    appId: '1:225418999366:android:bd23a76658170d67f8fc47',
    messagingSenderId: '225418999366',
    projectId: 'fypar-819e4',
    storageBucket: 'fypar-819e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3gxlviBkr485ACzTIkqkj2bqbGLr2SCk',
    appId: '1:225418999366:ios:bcf9f4dfe81bd210f8fc47',
    messagingSenderId: '225418999366',
    projectId: 'fypar-819e4',
    storageBucket: 'fypar-819e4.appspot.com',
    androidClientId: '225418999366-45nnbfc0brt923kuqnt2i2i72pafui23.apps.googleusercontent.com',
    iosClientId: '225418999366-jf2vim0gfkp0j4lm4gf7pq2kf1c1s5gl.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseStorageImage',
  );
}
